apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pmc-web-pro.fullname" . }}
  labels:
    {{- include "pmc-web-pro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pmc-web-pro.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pmc-web-pro.selectorLabels" . | nindent 8 }}
      annotations:
        timestamp: "{{ .Values.timestamp }}"
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "pmc-web-pro.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.preconfigureCommand }}
          command:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          env:
          - name: SECRET_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                key: environment
                name: pmc-secret-web-environment
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
