apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pmc-analizer.fullname" . }}
  labels:
    {{- include "pmc-analizer.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "pmc-analizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: "{{ .Values.timestamp }}"
      labels:
        {{- include "pmc-analizer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pmc-analizer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.version}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
          env:
          - name: SECRET_EMAIL_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: pmc-secret-email
          - name: SECRET_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: pmc-secret-email
          - name: SECRET_DB_URL
            valueFrom:
              secretKeyRef:
                key: url
                name: pmc-secret-db
          - name: SECRET_DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: pmc-secret-db
          - name: SECRET_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: pmc-secret-db
          - name: SECRET_DB_SCHEMA
            valueFrom:
              secretKeyRef:
                key: schema
                name: pmc-secret-db
          - name: WHATSAPP_URL
            valueFrom:
              secretKeyRef:
                key: whastapp.url
                name: pmc-secret-whatsapp
          - name: WHATSAPP_TOKEN
            valueFrom:
              secretKeyRef:
                key: whastapp.token
                name: pmc-secret-whatsapp
          - name: WHATSAPP_KILOMETROS
            valueFrom:
              secretKeyRef:
                key: whastapp.kilometros
                name: pmc-secret-whatsapp
          - name: WHATSAPP_NOTIFICA_SOLICITA
            valueFrom:
              secretKeyRef:
                key: whastapp.notifica.solicitante
                name: pmc-secret-whatsapp
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: cloudsql-proxy
          image: "{{ .Values.gcloud.repository }}:{{ .Values.gcloud.version }}" 
          imagePullPolicy: {{ .Values.gcloud.pullPolicy }}
          {{- with .Values.preconfigureCommand }}
          command:
            {{- toYaml . | nindent 10 }}
          {{- end }}          
          volumeMounts:
          - mountPath: /secrets/cloudsql
            name: pmc-secret-db-proxy 
      volumes:
      - name: pmc-secret-db-proxy
        secret:
          secretName: pmc-secret-db-proxy     
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
