apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
  creationTimestamp: "2020-03-24T06:03:10Z"
  generation: 14
  labels:
    app: pmc-service
  name: pmc-service
  namespace: default
  resourceVersion: "3134533"
  selfLink: /apis/apps/v1/namespaces/default/deployments/pmc-service
  uid: 23b2cf34-6d95-11ea-b62a-42010a8002bf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pmc-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pmc-service
    spec:
      containers:
      - env:
        - name: SECRET_EMAIL_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: pmc-secret-email
        - name: SECRET_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pmc-secret-email
        - name: URL_CONFIRM_TOKEN
          valueFrom:
            secretKeyRef:
              key: url.confirm.token
              name: pmc-secret-platform
        - name: SECRET_DB_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: pmc-secret-db
        - name: SECRET_DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: pmc-secret-db
        - name: SECRET_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pmc-secret-db
        - name: SECRET_DB_SCHEMA
          valueFrom:
            secretKeyRef:
              key: schema
              name: pmc-secret-db
        image: gcr.io/plataforma-mexico-covid19/pmc-service:0.0.5
        imagePullPolicy: IfNotPresent
        name: pmc-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /cloud_sql_proxy
        - -instances=plataforma-mexico-covid19:us-central1:pmc-db=tcp:3306
        - -credential_file=/secrets/cloudsql/plataforma-mexico-covid19-5b6a2f5c8084.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: pmc-secret-db-proxy
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pmc-secret-db-proxy
        secret:
          defaultMode: 420
          secretName: pmc-secret-db-proxy
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-24T06:03:10Z"
    lastUpdateTime: "2020-04-03T08:09:25Z"
    message: ReplicaSet "pmc-service-5fdfd8f768" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-03T21:27:08Z"
    lastUpdateTime: "2020-04-03T21:27:08Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 14
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
